# Generated by Django 2.1 on 2018-10-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181013_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_books',
        ),
    ]
