# Generated by Django 2.1.2 on 2018-10-09 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion')),
                ('amount_pages', models.IntegerField(verbose_name='Cantidad de paginas')),
                ('amount_chapter', models.IntegerField(verbose_name='Cantidad de capitulos')),
                ('pub_date', models.DateTimeField(verbose_name='Publicado')),
                ('recommended', models.IntegerField(default=0, verbose_name='Veces Recomendado')),
                ('content_adult', models.BooleanField(default=1, verbose_name='Solo para adultos?')),
                ('public', models.BooleanField(default=0, verbose_name='Publico')),
                ('file_book', models.FileField(default='', upload_to='static/uploads/%Y/%m/%d/', verbose_name='Libro')),
                ('img_book', models.ImageField(default='', upload_to='static/uploads/%Y/%m/%d/', verbose_name='Foto Portada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Gender', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
