# Generated by Django 2.1 on 2018-10-15 03:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20181014_2038'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gender',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
