# Generated by Django 2.1 on 2018-10-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20181015_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_book',
            field=models.FileField(default='', upload_to='', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img_book',
            field=models.ImageField(default='', upload_to='', verbose_name='Foto Portada'),
        ),
    ]
