# Generated by Django 2.1 on 2018-10-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='book',
        ),
    ]
