# Generated by Django 2.1 on 2018-10-16 03:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_download_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('authors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Download',
        ),
    ]
